New plugin "IP_Statistics_and_ASN"
unrealircd/unrealircd-webpanel-plugins pull request #3
Opened 2024-07-20 18:02 UTC by Madriix

New basic plugin that provides an overview of the most used ASNs, ranked from the highest to the lowest number of connected users. It also displays IP clones and IPv4 clones for the first four segments in /64.

I also thought of creating a new column 'Is it a VPN/Proxy?' with, for example, a green check icon or a 'Y', whenever an IP from the same ASN has already been detected as a VPN by a third-party API that detects VPNs. However, implementation is complicated because it requires retrieving the ASN for each scanned IP to check if it is a VPN or not.

2024-07-24 18:59 UTC, ValwareIRC requested changes
Nice work on the plugin! Good to see someone interested in making a plugin for the webpanel. I do just have a couple of reviews for you to see. :)

2024-07-24 18:59 UTC, ValwareIRC commented on IPCloneDetectorAndASNAnalyzer/IPCloneDetectorAndASNAnalyzer.php
> +  @version 1.0
You have a version mismatch with the version in the class name - these should match :D

2024-07-24 18:59 UTC, ValwareIRC commented on IPCloneDetectorAndASNAnalyzer/IPCloneDetectorAndASNAnalyzer.php
> +  @icon https://github.com/unrealircd/unrealircd-webpanel-plugins/blob/main/example_plugin/screenshots/example_icon.png?raw=true
Please could you use your own icons and screenshots instead of the ones from the example plugin

2024-07-24 18:59 UTC, ValwareIRC commented on IPCloneDetectorAndASNAnalyzer/badasn/README.md
A few things I would like to comment about:
- This file and its contents won't be seen via the webpanel, only the readme at the base of your plugin will be seen
- You can view in other plugins how to add and change things in the database. There is a global method which automatically "just works" with either sql or file database.
- Not particularly my concern given this is third-party, but I'm not sure I agree with your idea of what is a "bad ASN", it seems quite opinionated against things that are normal for IRC usage, such as VPN, proxy, server, like a bouncer or user's additional privacy.  That said, I would be fine with that if you added a disclaimer or some choices for the webpanel admin to choose what they think is a "bad ASN" because I think it would vary from network to network.

2024-07-25 00:00 UTC, Madriix commented
@ValwareIRC I have just made all the changes. Can you check if everything is correct?

2024-07-25 00:14 UTC, ValwareIRC approved these changes

2024-07-25 00:14 UTC, merged

2024-07-25 00:20 UTC, ValwareIRC commented
Oops, I just noticed you didn't put a contact email. Please would you mind updating your plugin to include it :D

2024-07-25 01:20 UTC, Madriix commented
@ValwareIRC I put an alias, you never know with spam bots